import { User, Request, RequestType, RequestStage, StageTransition, RequestedBy } from '@/types';
import { addBusinessHours, BUSINESS_HOURS } from './tat';

/**
 * Sample user data based on real team CSV
 */
export const SAMPLE_USERS: User[] = [
  {
    id: 'user-lalit-bhardwaj',
    employee_code: 'SBL0055',
    name: 'Lalit Bhardwaj',
    email: 'lalit.bhardwaj@squareyards.com',
    level: 'S3',
    location: 'Gurugram - M3M First Floor',
    designation: 'AVP - Brand Design',
    department: 'Marketing',
    supervisor_code: 'SQY44089',
    supervisor_name: 'Divya Krishnan',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-nitin-kumar',
    employee_code: 'SBL0065',
    name: 'Nitin Kumar',
    email: 'nitin.kumar@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Manager - SEO',
    department: 'Marketing',
    supervisor_code: 'SQY59542',
    supervisor_name: 'Shivam Chanana',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-rohit-rajoriya',
    employee_code: 'SBL0105',
    name: 'Rohit Rajoriya',
    email: 'rohit.rajoriya@squareyards.com',
    level: 'S2',
    location: 'Mumbai Ackruti Star 702',
    designation: 'Senior Manager',
    department: 'Marketing',
    supervisor_code: 'SQY44089',
    supervisor_name: 'Divya Krishnan',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-sukhmani',
    employee_code: 'SDC4035',
    name: 'Sukhmani',
    email: 'sukhmani@squareyards.com',
    level: 'S3',
    location: 'Gurugram - M3M First Floor',
    designation: 'Associate Vice President',
    department: 'Marketing',
    supervisor_code: 'SQY44089',
    supervisor_name: 'Divya Krishnan',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-sunita-kumari',
    employee_code: 'SDC4564',
    name: 'Sunita Kumari',
    email: 'sunita.kumari@squareyards.com',
    level: 'S2',
    location: 'Gurugram - M3M First Floor',
    designation: 'Manager - Brand Design',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-sandeep-chaurasia',
    employee_code: 'SDC4682',
    name: 'Sandeep Chaurasia',
    email: 'sandeep.chaurasia@squareyards.com',
    level: 'S2',
    location: 'Gurugram - M3M First Floor',
    designation: 'Brand Design Lead',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-divya-garg',
    employee_code: 'SDC4963',
    name: 'Divya Garg',
    email: 'divya.garg@squareyards.com',
    level: 'S2',
    location: 'Gurugram - M3M First Floor',
    designation: 'Manager - Brand Design',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-shiv-kumar-gupta',
    employee_code: 'SDC5026',
    name: 'Shiv Kumar Gupta',
    email: 'shiv.kumar.gupta@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Manager - SEO',
    department: 'Marketing',
    supervisor_code: 'SQY59542',
    supervisor_name: 'Shivam Chanana',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-gaurav-dhiman',
    employee_code: 'SDC5216',
    name: 'Gaurav Dhiman',
    email: 'gaurav.dhiman@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'SEO Executive',
    department: 'Marketing',
    supervisor_code: 'SDC5674',
    supervisor_name: 'Vikesh Verma',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-ashish-singh',
    employee_code: 'SDC5405',
    name: 'Ashish Singh',
    email: 'ashish.singh@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Product Manager',
    department: 'Marketing',
    supervisor_code: 'SQY44089',
    supervisor_name: 'Divya Krishnan',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-kunal-sachdeva',
    employee_code: 'SDC5595',
    name: 'Kunal Sachdeva',
    email: 'kunal.sachdeva@squareyards.com',
    level: 'S2',
    location: 'Gurugram - M3M First Floor',
    designation: 'Associate General Manager - Content',
    department: 'Marketing',
    supervisor_code: 'SQY59401',
    supervisor_name: 'Sunita Mishra',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-vimal-vijayan',
    employee_code: 'SDC5596',
    name: 'Vimal Vijayan',
    email: 'vimal.vijayan@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Senior Content Editor',
    department: 'Marketing',
    supervisor_code: 'SDC5595',
    supervisor_name: 'Kunal Sachdeva',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-supriya-boruah',
    employee_code: 'SBL2166',
    name: 'Supriya Boruah',
    email: 'supriya.boruah@squareyards.com',
    level: 'S1',
    location: 'Mumbai Ackruti Star 702',
    designation: 'Senior Executive - Marketing',
    department: 'Marketing',
    supervisor_code: 'SBL0105',
    supervisor_name: 'Rohit Rajoriya',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-vikesh-verma',
    employee_code: 'SDC5674',
    name: 'Vikesh Verma',
    email: 'vikesh.verma@squareyards.com',
    level: 'S2',
    location: 'Gurugram - M3M First Floor',
    designation: 'Associate General Manager - SEO',
    department: 'Marketing',
    supervisor_code: 'SQY59542',
    supervisor_name: 'Shivam Chanana',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-abhishek-kumar-singh',
    employee_code: 'SQY35817',
    name: 'Abhishek Kumar Singh',
    email: 'abhishek.kumar.singh@squareyards.com',
    level: 'S2',
    location: 'Gurugram - M3M First Floor',
    designation: 'Associate General Manager - SEO',
    department: 'Marketing',
    supervisor_code: 'SQY59542',
    supervisor_name: 'Shivam Chanana',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-karan-deep',
    employee_code: 'SQY36075',
    name: 'Karan Deep',
    email: 'karan.deep@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Web Developer',
    department: 'Marketing',
    supervisor_code: 'SQY56122',
    supervisor_name: 'Paramjeet',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-ankur-rawat',
    employee_code: 'SQY38120',
    name: 'Ankur Rawat',
    email: 'ankur.rawat@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Associate Manager - CMS',
    department: 'Marketing',
    supervisor_code: 'SQY59542',
    supervisor_name: 'Shivam Chanana',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-chaitali-sudhir-manjrekar',
    employee_code: 'SBL2609',
    name: 'Chaitali Sudhir Manjrekar',
    email: 'chaitali.sudhir.manjrekar@squareyards.com',
    level: 'S1',
    location: 'Mumbai Ackruti Star 702',
    designation: 'Marketing Executive',
    department: 'Marketing',
    supervisor_code: 'SBL0105',
    supervisor_name: 'Rohit Rajoriya',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-shweta-tawade',
    employee_code: 'SBL2638',
    name: 'Shweta Tawade',
    email: 'shweta.tawade@squareyards.com',
    level: 'S1',
    location: 'Mumbai Ackruti Star 702',
    designation: 'Marketing Executive',
    department: 'Marketing',
    supervisor_code: 'SBL0105',
    supervisor_name: 'Rohit Rajoriya',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-rishabh-baisoy',
    employee_code: 'SQY42700',
    name: 'Rishabh Baisoy',
    email: 'rishabh.baisoy@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Senior Content Writer',
    department: 'Marketing',
    supervisor_code: 'SDC5595',
    supervisor_name: 'Kunal Sachdeva',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-divya-krishnan',
    employee_code: 'SQY44089',
    name: 'Divya Krishnan',
    email: 'divya.krishnan@squareyards.com',
    level: 'SP&L',
    location: 'Dubai',
    designation: 'Head of Design',
    department: 'Marketing',
    supervisor_code: 'SYME001',
    supervisor_name: 'Kanika Gupta',
    role: 'admin',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-shubham-sandhu',
    employee_code: 'SQY46789',
    name: 'Shubham Sandhu',
    email: 'shubham.sandhu@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Content Writer',
    department: 'Marketing',
    supervisor_code: 'SDC5595',
    supervisor_name: 'Kunal Sachdeva',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-thejus-k-s',
    employee_code: 'SQY46790',
    name: 'Thejus K S',
    email: 'thejus.k.s@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Content Writer',
    department: 'Marketing',
    supervisor_code: 'SDC5595',
    supervisor_name: 'Kunal Sachdeva',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-rahul-gautam',
    employee_code: 'SQY51435',
    name: 'Rahul Gautam',
    email: 'rahul.gautam@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Content Writer',
    department: 'Marketing',
    supervisor_code: 'SDC5595',
    supervisor_name: 'Kunal Sachdeva',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-john-westly-antony',
    employee_code: 'SDC6287',
    name: 'John Westly Antony',
    email: 'john.westly.antony@squareyards.com',
    level: 'S1',
    location: 'Dubai',
    designation: 'Senior Videographer and Editor',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-bhavika-anant-modsing',
    employee_code: 'SQY54135',
    name: 'Bhavika Anant Modsing',
    email: 'bhavika.anant.modsing@squareyards.com',
    level: 'S1',
    location: 'Mumbai Ackruti Star 702',
    designation: 'Marketing Executive',
    department: 'Marketing',
    supervisor_code: 'SBL0105',
    supervisor_name: 'Rohit Rajoriya',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-devansh-sharma',
    employee_code: 'SQY54136',
    name: 'Devansh Sharma',
    email: 'devansh.sharma@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Associate Manager - Google Analytics',
    department: 'Marketing',
    supervisor_code: 'SQY59542',
    supervisor_name: 'Shivam Chanana',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-ritika-tyagi',
    employee_code: 'SQY54370',
    name: 'Ritika Tyagi',
    email: 'ritika.tyagi@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Marketing Executive',
    department: 'Marketing',
    supervisor_code: 'SDC4035',
    supervisor_name: 'Sukhmani',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-bharath-subramani',
    employee_code: 'SQY55352',
    name: 'Bharath Subramani',
    email: 'bharath.subramani@squareyards.com',
    level: 'S1',
    location: 'Dubai',
    designation: 'Senior Executive - Performance Marketing',
    department: 'Marketing',
    supervisor_code: 'SQY44089',
    supervisor_name: 'Divya Krishnan',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-aaryan-sharma',
    employee_code: 'SQY55706',
    name: 'Aaryan Sharma',
    email: 'aaryan.sharma@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Social Media Executive',
    department: 'Marketing',
    supervisor_code: 'SDC4035',
    supervisor_name: 'Sukhmani',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-ankit-rawat',
    employee_code: 'SQY55707',
    name: 'Ankit Rawat',
    email: 'ankit.rawat@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Senior Video Editor',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-prakriti-singh',
    employee_code: 'SQY55708',
    name: 'Prakriti Singh',
    email: 'prakriti.singh@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Social Media Executive',
    department: 'Marketing',
    supervisor_code: 'SDC4035',
    supervisor_name: 'Sukhmani',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-abhay-gupta',
    employee_code: 'SQY55953',
    name: 'Abhay Gupta',
    email: 'abhay.gupta@squareyards.com',
    level: 'S1',
    location: 'Mumbai Ackruti Star 702',
    designation: 'Senior Videographer and Editor',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-namita-aggarwal',
    employee_code: 'SQY55954',
    name: 'Namita Aggarwal',
    email: 'namita.aggarwal@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Senior Graphic Designer',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-sudhir',
    employee_code: 'SQY56101',
    name: 'Sudhir',
    email: 'sudhir@squareyards.com',
    level: 'S2',
    location: 'Gurugram - M3M First Floor',
    designation: 'Manager Performance Marketing',
    department: 'Marketing',
    supervisor_code: 'SQY56122',
    supervisor_name: 'Paramjeet',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-paramjeet',
    employee_code: 'SQY56122',
    name: 'Paramjeet',
    email: 'paramjeet@squareyards.com',
    level: 'S2',
    location: 'Gurugram - M3M First Floor',
    designation: 'Manager Performance Marketing',
    department: 'Marketing',
    supervisor_code: 'SQY44089',
    supervisor_name: 'Divya Krishnan',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-raj-gaurav',
    employee_code: 'SIN3939',
    name: 'Raj Gaurav',
    email: 'raj.gaurav@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Intern',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-parth-sharma',
    employee_code: 'SQY56333',
    name: 'Parth Sharma',
    email: 'parth.sharma@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Marketing Lead',
    department: 'Marketing',
    supervisor_code: 'SDC4035',
    supervisor_name: 'Sukhmani',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-garima-banwala',
    employee_code: 'SQY56416',
    name: 'Garima Banwala',
    email: 'garima.banwala@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Senior Graphic Designer',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-akash-bhatt',
    employee_code: 'SQY56773',
    name: 'Akash Bhatt',
    email: 'akash.bhatt@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Video Editor',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-ashish-kumar',
    employee_code: 'SQY56974',
    name: 'Ashish Kumar',
    email: 'ashish.kumar@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M Second Floor',
    designation: 'Senior Investment Manager',
    department: 'Marketing',
    supervisor_code: 'SDC4035',
    supervisor_name: 'Sukhmani',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-piyush-sharma',
    employee_code: 'SQY57146',
    name: 'Piyush Sharma',
    email: 'piyush.sharma@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Marketing Executive',
    department: 'Marketing',
    supervisor_code: 'SQY56333',
    supervisor_name: 'Parth Sharma',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-rishabh-singh',
    employee_code: 'SQY57180',
    name: 'Rishabh Singh',
    email: 'rishabh.singh@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Graphic Designer',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-sidharth-bharti',
    employee_code: 'SQY57973',
    name: 'Sidharth Bharti',
    email: 'sidharth.bharti@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Graphic Designer',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-pranjal-sapra',
    employee_code: 'SQY58633',
    name: 'Pranjal Sapra',
    email: 'pranjal.sapra@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Senior Content Writer',
    department: 'Marketing',
    supervisor_code: 'SDC4035',
    supervisor_name: 'Sukhmani',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-mitesh-kumar-singh',
    employee_code: 'SQY58651',
    name: 'Mitesh Kumar Singh',
    email: 'mitesh.kumar.singh@squareyards.com',
    level: 'S2',
    location: 'Gurugram - M3M First Floor',
    designation: 'Associate General Manager - SEO',
    department: 'Marketing',
    supervisor_code: 'SQY59542',
    supervisor_name: 'Shivam Chanana',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-abheet-chawla',
    employee_code: 'SQY58858',
    name: 'Abheet Chawla',
    email: 'abheet.chawla@squareyards.com',
    level: 'S2',
    location: 'Gurugram - M3M First Floor',
    designation: 'Content Manager',
    department: 'Marketing',
    supervisor_code: 'SDC5595',
    supervisor_name: 'Kunal Sachdeva',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-rahul-chatterjee',
    employee_code: 'SQY58916',
    name: 'Rahul Chatterjee',
    email: 'rahul.chatterjee@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Video Editor',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-sakshi-saxena',
    employee_code: 'SDC6596',
    name: 'Sakshi Saxena',
    email: 'sakshi.saxena@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Senior Manager: Research and Media Outreach',
    department: 'Marketing',
    supervisor_code: 'SQY59401',
    supervisor_name: 'Sunita Mishra',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-abigail-venessa-simmons',
    employee_code: 'SQY59196',
    name: 'Abigail Venessa Simmons',
    email: 'abigail.venessa.simmons@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Content Writer',
    department: 'Marketing',
    supervisor_code: 'SDC5595',
    supervisor_name: 'Kunal Sachdeva',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-drishti-katyal',
    employee_code: 'SQY59215',
    name: 'Drishti Katyal',
    email: 'drishti.katyal@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Content Writer',
    department: 'Marketing',
    supervisor_code: 'SDC5595',
    supervisor_name: 'Kunal Sachdeva',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-sunita-mishra',
    employee_code: 'SQY59401',
    name: 'Sunita Mishra',
    email: 'sunita.mishra@squareyards.com',
    level: 'S3',
    location: 'Gurugram - M3M First Floor',
    designation: 'Content Strategy Head',
    department: 'Marketing',
    supervisor_code: 'SQY44089',
    supervisor_name: 'Divya Krishnan',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-muskan-shafi',
    employee_code: 'SQY59407',
    name: 'Muskan Shafi',
    email: 'muskan.shafi@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Senior Content Writer',
    department: 'Marketing',
    supervisor_code: 'SDC5595',
    supervisor_name: 'Kunal Sachdeva',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-shivam-chanana',
    employee_code: 'SQY59542',
    name: 'Shivam Chanana',
    email: 'shivam.chanana@squareyards.com',
    level: 'S2',
    location: 'Gurugram - M3M First Floor',
    designation: 'Associate General Manager - SEO',
    department: 'Marketing',
    supervisor_code: 'SQY44089',
    supervisor_name: 'Divya Krishnan',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-diva-bindal',
    employee_code: 'SIN3981',
    name: 'Diva Bindal',
    email: 'diva.bindal@squareyards.com',
    level: 'SE',
    location: 'Gurugram - M3M First Floor',
    designation: 'Intern',
    department: 'Marketing',
    supervisor_code: 'SQY60797',
    supervisor_name: 'Dhruv Thakur',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-aditi-arora',
    employee_code: 'SQY59715',
    name: 'Aditi Arora',
    email: 'aditi.arora@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Marketing Executive',
    department: 'Marketing',
    supervisor_code: 'SQY60797',
    supervisor_name: 'Dhruv Thakur',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-jyotsna-santosh-chudji',
    employee_code: 'SQY59917',
    name: 'Jyotsna Santosh Chudji',
    email: 'jyotsna.santosh.chudji@squareyards.com',
    level: 'S0',
    location: 'Mumbai Ackruti Star 701',
    designation: 'Marketing Executive',
    department: 'Marketing',
    supervisor_code: 'SBL0105',
    supervisor_name: 'Rohit Rajoriya',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-tanishka-jamwal',
    employee_code: 'SQY59928',
    name: 'Tanishka Jamwal',
    email: 'tanishka.jamwal@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Marketing Executive',
    department: 'Marketing',
    supervisor_code: 'SDC5405',
    supervisor_name: 'Ashish Singh',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-aditya-kumar-mishra',
    employee_code: 'SIN3991',
    name: 'Aditya Kumar Mishra',
    email: 'aditya.kumar.mishra@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'SEO Intern',
    department: 'Marketing',
    supervisor_code: 'SQY59542',
    supervisor_name: 'Shivam Chanana',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-chinmay-gaur',
    employee_code: 'SQY60167',
    name: 'Chinmay Gaur',
    email: 'chinmay.gaur@squareyards.com',
    level: 'S1',
    location: 'Gurugram - M3M First Floor',
    designation: 'Generative Engine Optimization',
    department: 'Marketing',
    supervisor_code: 'SQY44089',
    supervisor_name: 'Divya Krishnan',
    role: 'designer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-prateek-jain',
    employee_code: 'SIN3994',
    name: 'Prateek Jain',
    email: 'prateek.jain@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Intern',
    department: 'Marketing',
    supervisor_code: 'SQY59542',
    supervisor_name: 'Shivam Chanana',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-riddhi-chatterji',
    employee_code: 'SQY60210',
    name: 'Riddhi Chatterji',
    email: 'riddhi.chatterji@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Content Writer',
    department: 'Marketing',
    supervisor_code: 'SQY59401',
    supervisor_name: 'Sunita Mishra',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-abhilasa-bhattacharya',
    employee_code: 'SQY60413',
    name: 'Abhilasa Bhattacharya',
    email: 'abhilasa.bhattacharya@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Senior Marketing Strategist',
    department: 'Marketing',
    supervisor_code: 'SDC4035',
    supervisor_name: 'Sukhmani',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-simran-shankar',
    employee_code: 'SQY60437',
    name: 'Simran Shankar',
    email: 'simran.shankar@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Marketing Executive',
    department: 'Marketing',
    supervisor_code: 'SDC4035',
    supervisor_name: 'Sukhmani',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-vishesh-paliwal',
    employee_code: 'SQY60597',
    name: 'Vishesh Paliwal',
    email: 'vishesh.paliwal@squareyards.com',
    level: 'S2',
    location: 'Gurugram - M3M First Floor',
    designation: 'Marketing Lead',
    department: 'Marketing',
    supervisor_code: 'SQY59542',
    supervisor_name: 'Shivam Chanana',
    role: 'manager',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-dhruv-thakur',
    employee_code: 'SQY60797',
    name: 'Dhruv Thakur',
    email: 'dhruv.thakur@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Copy Lead',
    department: 'Marketing',
    supervisor_code: 'SDC4035',
    supervisor_name: 'Sukhmani',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-harshita-bansal',
    employee_code: 'SIN4006',
    name: 'Harshita Bansal',
    email: 'harshita.bansal@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Intern',
    department: 'Marketing',
    supervisor_code: 'SQY59542',
    supervisor_name: 'Shivam Chanana',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-himani-rajput',
    employee_code: 'SQY60844',
    name: 'Himani Rajput',
    email: 'himani.rajput@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Video Editor',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-amit-kumar',
    employee_code: 'SQY60845',
    name: 'Amit Kumar',
    email: 'amit.kumar@squareyards.com',
    level: 'S0',
    location: 'Gurugram - M3M First Floor',
    designation: 'Video Editor',
    department: 'Marketing',
    supervisor_code: 'SBL0055',
    supervisor_name: 'Lalit Bhardwaj',
    role: 'viewer',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Requests
// ─────────────────────────────────────────────────────────────────────────────

export const SAMPLE_REQUESTS: Request[] = [];

// ─────────────────────────────────────────────────────────────────────────────
// Helper exports (used by existing pages + new performance pages)
// ─────────────────────────────────────────────────────────────────────────────

/** Format a Date/ISO string as YYYY-MM-DD. */
export function formatDate(date: string | Date): string {
  if (typeof date === 'string') {
    return date.split('T')[0];
  }
  return date.toISOString().split('T')[0];
}

export function getStagesForType(type: RequestType): RequestStage[] {
  switch (type) {
    case 'Video':
      return [
        'Assigned', 'Planning', 'Shooting Scheduled', 'Shoot Done',
        'Editing In Progress', 'Editing Done', 'Ready to Upload',
        'Change Req', 'Uploaded',
      ];
    case 'Social Media Graphics':
    case 'Graphics':
      return [
        'Assigned', 'Content', 'Design In Progress', 'Design Done',
        'Ready to Upload', 'Change Req', 'Done',
      ];
    default:
      return [];
  }
}

export function getUserById(userId?: string): User | undefined {
  if (!userId) return undefined;
  return SAMPLE_USERS.find((u) => u.id === userId);
}

export function getInitials(name: string): string {
  return name
    .split(' ')
    .map((n) => n[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);
}

export function isFinal(req: Request): boolean {
  return req.current_stage === 'Done' || req.current_stage === 'Uploaded' ||
    req.current_stage === 'Ready to Upload';
}

export function isFinalStage(req: Request): boolean {
  return isFinal(req);
}

export function isOverdue(needBy: string | Request): boolean {
  let needByDate: Date;
  let finalRequest = false;

  if (typeof needBy === 'string') {
    needByDate = new Date(needBy);
  } else {
    needByDate = new Date(needBy.need_by);
    finalRequest = isFinal(needBy);
  }

  if (finalRequest) {
    return false;
  }

  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return needByDate < today;
}

export function getDaysUntilDue(needBy: string): number {
  const needByDate = new Date(needBy);
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  needByDate.setHours(0, 0, 0, 0);
  const diffTime = needByDate.getTime() - today.getTime();
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
}

/**
 * Calculate days spent in a given stage (approximation for legacy pages).
 * Prefer the business-hours functions in `@/lib/tat` for real calculations.
 */
export function getStageTAT(
  req: Request,
  fromStage: string,
  toStage: string
): number {
  const transitions = req.transitions ?? [];
  const fromT = transitions.find((t) => t.to_stage === fromStage);
  const toT = transitions.find((t) => t.to_stage === toStage);
  if (!fromT || !toT) return 0;
  const diff = new Date(toT.transitioned_at).getTime() - new Date(fromT.transitioned_at).getTime();
  return Math.max(0, Math.ceil(diff / (1000 * 60 * 60 * 24)));
}

/**
 * Total calendar days from creation to latest transition (legacy helper).
 */
export function getTotalTAT(req: Request): number {
  const created = new Date(req.created_at).getTime();
  const transitions = req.transitions ?? [];
  const last = transitions.length
    ? new Date(transitions[transitions.length - 1].transitioned_at).getTime()
    : new Date(req.updated_at).getTime();
  const diff = Math.max(0, last - created);
  return Math.max(1, Math.ceil(diff / (1000 * 60 * 60 * 24)));
}
