-- Seed data for users table with 69 team members from Marketing Beats CSV
-- Level to Role mapping: SP&L → admin, S3 → manager, S2 → manager, S1 → designer, S0 → viewer, SE → viewer

INSERT INTO users (employee_code, name, email, level, location, designation, department, supervisor_code, supervisor_name, role, is_active) VALUES
('SBL0055', 'Lalit Bhardwaj', 'lalit.bhardwaj@squareyards.com', 'S3', 'Gurugram - M3M First Floor', 'AVP - Brand Design', 'Marketing', 'SQY44089', 'Divya Krishnan', 'manager', true),
('SBL0065', 'Nitin Kumar', 'nitin.kumar@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Manager - SEO', 'Marketing', 'SQY59542', 'Shivam Chanana', 'designer', true),
('SBL0105', 'Rohit Rajoriya', 'rohit.rajoriya@squareyards.com', 'S2', 'Mumbai Ackruti Star 702', 'Senior Manager', 'Marketing', 'SQY44089', 'Divya Krishnan', 'manager', true),
('SDC4035', 'Sukhmani', 'sukhmani@squareyards.com', 'S3', 'Gurugram - M3M First Floor', 'Associate Vice President', 'Marketing', 'SQY44089', 'Divya Krishnan', 'manager', true),
('SDC4564', 'Sunita Kumari', 'sunita.kumari@squareyards.com', 'S2', 'Gurugram - M3M First Floor', 'Manager - Brand Design', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'manager', true),
('SDC4682', 'Sandeep Chaurasia', 'sandeep.chaurasia@squareyards.com', 'S2', 'Gurugram - M3M First Floor', 'Brand Design Lead', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'manager', true),
('SDC4963', 'Divya Garg', 'divya.garg@squareyards.com', 'S2', 'Gurugram - M3M First Floor', 'Manager - Brand Design', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'manager', true),
('SDC5026', 'Shiv Kumar Gupta', 'shiv.kumar.gupta@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Manager - SEO', 'Marketing', 'SQY59542', 'Shivam Chanana', 'designer', true),
('SDC5216', 'Gaurav Dhiman', 'gaurav.dhiman@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'SEO Executive', 'Marketing', 'SDC5674', 'Vikesh Verma', 'designer', true),
('SDC5405', 'Ashish Singh', 'ashish.singh@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Product Manager', 'Marketing', 'SQY44089', 'Divya Krishnan', 'designer', true),
('SDC5595', 'Kunal Sachdeva', 'kunal.sachdeva@squareyards.com', 'S2', 'Gurugram - M3M First Floor', 'Associate General Manager - Content', 'Marketing', 'SQY59401', 'Sunita Mishra', 'manager', true),
('SDC5596', 'Vimal Vijayan', 'vimal.vijayan@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Senior Content Editor', 'Marketing', 'SDC5595', 'Kunal Sachdeva', 'designer', true),
('SBL2166', 'Supriya Boruah', 'supriya.boruah@squareyards.com', 'S1', 'Mumbai Ackruti Star 702', 'Senior Executive - Marketing', 'Marketing', 'SBL0105', 'Rohit Rajoriya', 'designer', true),
('SDC5674', 'Vikesh Verma', 'vikesh.verma@squareyards.com', 'S2', 'Gurugram - M3M First Floor', 'Associate General Manager - SEO', 'Marketing', 'SQY59542', 'Shivam Chanana', 'manager', true),
('SQY35817', 'Abhishek Kumar Singh', 'abhishek.kumar.singh@squareyards.com', 'S2', 'Gurugram - M3M First Floor', 'Associate General Manager - SEO', 'Marketing', 'SQY59542', 'Shivam Chanana', 'manager', true),
('SQY36075', 'Karan Deep', 'karan.deep@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Web Developer', 'Marketing', 'SQY56122', 'Paramjeet', 'designer', true),
('SQY38120', 'Ankur Rawat', 'ankur.rawat@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Associate Manager - CMS', 'Marketing', 'SQY59542', 'Shivam Chanana', 'designer', true),
('SBL2609', 'Chaitali Sudhir Manjrekar', 'chaitali.sudhir.manjrekar@squareyards.com', 'S1', 'Mumbai Ackruti Star 702', 'Marketing Executive', 'Marketing', 'SBL0105', 'Rohit Rajoriya', 'designer', true),
('SBL2638', 'Shweta Tawade', 'shweta.tawade@squareyards.com', 'S1', 'Mumbai Ackruti Star 702', 'Marketing Executive', 'Marketing', 'SBL0105', 'Rohit Rajoriya', 'designer', true),
('SQY42700', 'Rishabh Baisoy', 'rishabh.baisoy@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Senior Content Writer', 'Marketing', 'SDC5595', 'Kunal Sachdeva', 'designer', true),
('SQY44089', 'Divya Krishnan', 'divya.krishnan@squareyards.com', 'SP&L', 'Dubai', 'Head of Design', 'Marketing', 'SYME001', 'Kanika Gupta', 'admin', true),
('SQY46789', 'Shubham Sandhu', 'shubham.sandhu@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Content Writer', 'Marketing', 'SDC5595', 'Kunal Sachdeva', 'designer', true),
('SQY46790', 'Thejus K S', 'thejus.k.s@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Content Writer', 'Marketing', 'SDC5595', 'Kunal Sachdeva', 'designer', true),
('SQY51435', 'Rahul Gautam', 'rahul.gautam@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Content Writer', 'Marketing', 'SDC5595', 'Kunal Sachdeva', 'designer', true),
('SDC6287', 'John Westly Antony', 'john.westly.antony@squareyards.com', 'S1', 'Dubai', 'Senior Videographer and Editor', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'designer', true),
('SQY54135', 'Bhavika Anant Modsing', 'bhavika.anant.modsing@squareyards.com', 'S1', 'Mumbai Ackruti Star 702', 'Marketing Executive', 'Marketing', 'SBL0105', 'Rohit Rajoriya', 'designer', true),
('SQY54136', 'Devansh Sharma', 'devansh.sharma@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Associate Manager - Google Analytics', 'Marketing', 'SQY59542', 'Shivam Chanana', 'designer', true),
('SQY54370', 'Ritika Tyagi', 'ritika.tyagi@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Marketing Executive', 'Marketing', 'SDC4035', 'Sukhmani', 'designer', true),
('SQY55352', 'Bharath Subramani', 'bharath.subramani@squareyards.com', 'S1', 'Dubai', 'Senior Executive - Performance Marketing', 'Marketing', 'SQY44089', 'Divya Krishnan', 'designer', true),
('SQY55706', 'Aaryan Sharma', 'aaryan.sharma@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Social Media Executive', 'Marketing', 'SDC4035', 'Sukhmani', 'designer', true),
('SQY55707', 'Ankit Rawat', 'ankit.rawat@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Senior Video Editor', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'designer', true),
('SQY55708', 'Prakriti Singh', 'prakriti.singh@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Social Media Executive', 'Marketing', 'SDC4035', 'Sukhmani', 'designer', true),
('SQY55953', 'Abhay Gupta', 'abhay.gupta@squareyards.com', 'S1', 'Mumbai Ackruti Star 702', 'Senior Videographer and Editor', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'designer', true),
('SQY55954', 'Namita Aggarwal', 'namita.aggarwal@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Senior Graphic Designer', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'designer', true),
('SQY56101', 'Sudhir', 'sudhir@squareyards.com', 'S2', 'Gurugram - M3M First Floor', 'Manager Performance Marketing', 'Marketing', 'SQY56122', 'Paramjeet', 'manager', true),
('SQY56122', 'Paramjeet', 'paramjeet@squareyards.com', 'S2', 'Gurugram - M3M First Floor', 'Manager Performance Marketing', 'Marketing', 'SQY44089', 'Divya Krishnan', 'manager', true),
('SIN3939', 'Raj Gaurav', 'raj.gaurav@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Intern', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'viewer', true),
('SQY56333', 'Parth Sharma', 'parth.sharma@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Marketing Lead', 'Marketing', 'SDC4035', 'Sukhmani', 'designer', true),
('SQY56416', 'Garima Banwala', 'garima.banwala@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Senior Graphic Designer', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'viewer', true),
('SQY56773', 'Akash Bhatt', 'akash.bhatt@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Video Editor', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'viewer', true),
('SQY56974', 'Ashish Kumar', 'ashish.kumar@squareyards.com', 'S0', 'Gurugram - M3M Second Floor', 'Senior Investment Manager', 'Marketing', 'SDC4035', 'Sukhmani', 'viewer', true),
('SQY57146', 'Piyush Sharma', 'piyush.sharma@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Marketing Executive', 'Marketing', 'SQY56333', 'Parth Sharma', 'viewer', true),
('SQY57180', 'Rishabh Singh', 'rishabh.singh@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Graphic Designer', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'viewer', true),
('SQY57973', 'Sidharth Bharti', 'sidharth.bharti@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Graphic Designer', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'viewer', true),
('SQY58633', 'Pranjal Sapra', 'pranjal.sapra@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Senior Content Writer', 'Marketing', 'SDC4035', 'Sukhmani', 'viewer', true),
('SQY58651', 'Mitesh Kumar Singh', 'mitesh.kumar.singh@squareyards.com', 'S2', 'Gurugram - M3M First Floor', 'Associate General Manager - SEO', 'Marketing', 'SQY59542', 'Shivam Chanana', 'manager', true),
('SQY58858', 'Abheet Chawla', 'abheet.chawla@squareyards.com', 'S2', 'Gurugram - M3M First Floor', 'Content Manager', 'Marketing', 'SDC5595', 'Kunal Sachdeva', 'manager', true),
('SQY58916', 'Rahul Chatterjee', 'rahul.chatterjee@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Video Editor', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'designer', true),
('SDC6596', 'Sakshi Saxena', 'sakshi.saxena@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Senior Manager: Research and Media Outreach', 'Marketing', 'SQY59401', 'Sunita Mishra', 'designer', true),
('SQY59196', 'Abigail Venessa Simmons', 'abigail.venessa.simmons@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Content Writer', 'Marketing', 'SDC5595', 'Kunal Sachdeva', 'designer', true),
('SQY59215', 'Drishti Katyal', 'drishti.katyal@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Content Writer', 'Marketing', 'SDC5595', 'Kunal Sachdeva', 'designer', true),
('SQY59401', 'Sunita Mishra', 'sunita.mishra@squareyards.com', 'S3', 'Gurugram - M3M First Floor', 'Content Strategy Head', 'Marketing', 'SQY44089', 'Divya Krishnan', 'manager', true),
('SQY59407', 'Muskan Shafi', 'muskan.shafi@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Senior Content Writer', 'Marketing', 'SDC5595', 'Kunal Sachdeva', 'designer', true),
('SQY59542', 'Shivam Chanana', 'shivam.chanana@squareyards.com', 'S2', 'Gurugram - M3M First Floor', 'Associate General Manager - SEO', 'Marketing', 'SQY44089', 'Divya Krishnan', 'manager', true),
('SIN3981', 'Diva Bindal', 'diva.bindal@squareyards.com', 'SE', 'Gurugram - M3M First Floor', 'Intern', 'Marketing', 'SQY60797', 'Dhruv Thakur', 'viewer', true),
('SQY59715', 'Aditi Arora', 'aditi.arora@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Marketing Executive', 'Marketing', 'SQY60797', 'Dhruv Thakur', 'viewer', true),
('SQY59917', 'Jyotsna Santosh Chudji', 'jyotsna.santosh.chudji@squareyards.com', 'S0', 'Mumbai Ackruti Star 701', 'Marketing Executive', 'Marketing', 'SBL0105', 'Rohit Rajoriya', 'viewer', true),
('SQY59928', 'Tanishka Jamwal', 'tanishka.jamwal@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Marketing Executive', 'Marketing', 'SDC5405', 'Ashish Singh', 'viewer', true),
('SIN3991', 'Aditya Kumar Mishra', 'aditya.kumar.mishra@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'SEO Intern', 'Marketing', 'SQY59542', 'Shivam Chanana', 'viewer', true),
('SQY60167', 'Chinmay Gaur', 'chinmay.gaur@squareyards.com', 'S1', 'Gurugram - M3M First Floor', 'Generative Engine Optimization', 'Marketing', 'SQY44089', 'Divya Krishnan', 'designer', true),
('SIN3994', 'Prateek Jain', 'prateek.jain@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Intern', 'Marketing', 'SQY59542', 'Shivam Chanana', 'viewer', true),
('SQY60210', 'Riddhi Chatterji', 'riddhi.chatterji@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Content Writer', 'Marketing', 'SQY59401', 'Sunita Mishra', 'viewer', true),
('SQY60413', 'Abhilasa Bhattacharya', 'abhilasa.bhattacharya@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Senior Marketing Strategist', 'Marketing', 'SDC4035', 'Sukhmani', 'viewer', true),
('SQY60437', 'Simran Shankar', 'simran.shankar@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Marketing Executive', 'Marketing', 'SDC4035', 'Sukhmani', 'viewer', true),
('SQY60597', 'Vishesh Paliwal', 'vishesh.paliwal@squareyards.com', 'S2', 'Gurugram - M3M First Floor', 'Marketing Lead', 'Marketing', 'SQY59542', 'Shivam Chanana', 'manager', true),
('SQY60797', 'Dhruv Thakur', 'dhruv.thakur@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Copy Lead', 'Marketing', 'SDC4035', 'Sukhmani', 'viewer', true),
('SIN4006', 'Harshita Bansal', 'harshita.bansal@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Intern', 'Marketing', 'SQY59542', 'Shivam Chanana', 'viewer', true),
('SQY60844', 'Himani Rajput', 'himani.rajput@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Video Editor', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'viewer', true),
('SQY60845', 'Amit Kumar', 'amit.kumar@squareyards.com', 'S0', 'Gurugram - M3M First Floor', 'Video Editor', 'Marketing', 'SBL0055', 'Lalit Bhardwaj', 'viewer', true);
